### ISSUE TITLE
[SECURESIGN-568] Sharding of the Rekor Log

### ISSUE THREAD

**Issue by osmman** [securesign/secure-sign-operator#78]
Extend operator functionality to enable sharding Rekor's log 

https://docs.sigstore.dev/logging/sharding/

**Comment by cooktheryan** [comment]
@osmman with this work would we want it to be the default configuration or an option?

**Comment by osmman** [comment]
This is use case for second day operation when you have to split into multiple Merkle trees. We will need extend api to configure sharding configuration. I expect that for default configuration it will work same way as current deployment (clean install use only single tree). 

It can look like this:
```
kind: Rekor
spec:
  sharding:
    - treeID: $OLD_TREE_ID
       treeLength: $OLD_SHARD_LENGTH
    - treeID: $CURRENT_TREE_ID
       treeLength: $CURRENT_SHARD_LENGTH
  treeID: $NEW_TREE_ID
```

More interesting part will be if we want to automate that whole process from [documentation](https://docs.sigstore.dev/logging/sharding/#how-do-i-shard-the-rekor-log) in Operator or users will have to do that manually.
